#!/bin/bash
#Total size 335Mb
#RS232 and VGA
apt-get install -y debootstrap qemu-utils

cd /var/lib/libvirt/images/
mkdir min_dist
cd min_dist

qemu-img create Debian7.img 1G
rmmod loop
modprobe loop max_part=15



losetup /dev/loop0 Debian7.img


partprobe /dev/loop0
mkfs.ext4 -F /dev/loop0p1
mkdir  /mnt/debian
mount -v /dev/loop0p1 /mnt/debian

debootstrap --verbose --include=sudo,nano,wget,grub-pc --arch amd64 wheezy /mnt/debian http://ftp.pt.debian.org/debian/

cat > /mnt/debian/etc/fstab << "EOF"
/dev/sda1       /               ext4        defaults        0       1
EOF

cat > /mnt/debian/etc/apt/sources.list << "EOF"
deb http://ftp.pt.debian.org/debian/ wheezy main contrib non-free
deb http://ftp.pt.debian.org/debian/ wheezy-updates main contrib non-free
deb http://security.debian.org/ wheezy/updates main contrib non-free
EOF

cat > /mnt/debian/root/postinst.sh << "EOF"
#!/bin/bash

apt-get update

useradd -m -s /bin/bash tester
passwd tester << "OEF"
tester
tester
OEF

passwd << "OEF"
admin
admin
OEF


apt-get -y install linux-image-amd64
#apt-get -y install firmware-linux firmware-ralink firmware-realtek
apt-get clean

sed -i 's/^#T0:23.*/T0:23:respawn:\/sbin\/getty -L ttyS0 115200 vt100/' /etc/inittab
sed -i 's/^#GRUB_TERMINAL.*/GRUB_TERMINAL="serial console"/' /etc/default/grub
sed -i 's/^GRUB_CMDLINE_LINUX.*/GRUB_CMDLINE_LINUX="console=ttyS0"/' /etc/default/grub

update-grub2
grub-install /dev/loop0 --modules="biosdisk part_msdos"
sed -i 's/\/dev\/loop0p1/\/dev\/sda1/g' /boot/grub/grub.cfg
sync
EOF


mount -v --bind /dev /mnt/debian/dev
mount -vt devpts devpts /mnt/debian/dev/pts
mount -vt proc proc /mnt/debian/proc
mount -vt sysfs sysfs /mnt/debian/sys
mount -vt tmpfs tmpfs /mnt/debian/run


chroot /mnt/debian /bin/bash /root/postinst.sh
chroot /mnt/debian /bin/bash -c "rm -rf /root/postinst.sh"


umount -v /mnt/debian/dev/pts
umount -v /mnt/debian/dev
umount -v /mnt/debian/proc
umount -v /mnt/debian/sys
umount -v /mnt/debian/run


umount -v /mnt/debian/
losetup -d /dev/loop0
